name: Java Maven CI

# Run the workflow on push to the main branch and on pull requests
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    # Step 3: Cache Maven dependencies to speed up build times
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    # Step 4: Build the project with Maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Step 5: Run tests with Maven
    - name: Run tests
      run: mvn test

    # Step 6: Create a JAR file for your application
    - name: Package the JAR file
      run: mvn package

